version: '3'

services:
  frontend:
    build:
      context: ./Frontend/my-portfolio
      dockerfile: Dockerfile
    image: hiransanjeewa/portfolio_client:latest

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    image: hiransanjeewa/portfolio_server:latest


# 2 nd New commit added 