name: Docker Image CI

on:
  push:
    branches: [ main ]
env:
  AWS_EC2_INSTANCE_IP: "3.83.134.214"
  DOCKER_IMAGE_NAME: portfolio
  DOCKERHUB_USERNAME: hiransanjeewa
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  

jobs:

  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Frontend/my-portfolio

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKERHUB_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag hiransanjeewa/portfolio:latest
        
    - name: Docker Push
      run: docker push hiransanjeewa/portfolio

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.1
      with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
      

   
         
         
       

      # - name: Change directory to my_portfolio
        # run: cd Frontend/Frontend/my_portfolio
