name: Build and Deploy

on:
  push:
    branches:
      - main
 

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Frontend/my-portfolio

    steps:
      - uses: actions/checkout@v1
      - name: Build & Push Image
        run: |
          echo "${{ secrets.DOCKERPW }}" | docker login -u "HiranSanjeewa" --password-stdin
          docker image build -t HiranSanjeewa/portfolio_frontend:latest .
          docker push HiranSanjeewa/portfolio_frontend:latest
   
          
          
         
         
       

      # - name: Change directory to my_portfolio
        # run: cd Frontend/Frontend/my_portfolio
