name: React CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Frontend/my-portfolio

    strategy:
      matrix:
        node-version: [18.x]
    

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './Frontend/my-portfolio/package-lock.json'
     
      - name: Install dependencies
        run: npm install --legacy-peer-deps
        # working-directory: ./subdirectory

      - name: building the app
        run: npm run build
        # working-directory: ./subdirectory
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
         
          
          
         
         
       

      # - name: Change directory to my_portfolio
        # run: cd Frontend/Frontend/my_portfolio
