name: Build and Deploy

on:
  push:
    branches:
      - main
 

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
   
          
          
         
         
       

      # - name: Change directory to my_portfolio
        # run: cd Frontend/Frontend/my_portfolio
