name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: [  "main" ]




env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: hiransanjeewa/portfolio
  EC2_INSTANCE_IP:  ${{ secrets.EC2_HOST }}     
  SSH_USERNAME: ubuntu
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}


jobs:
 build-push-gcr:
    name: Building Docker and Pushing images
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
          node-version: 14

    




    - name: Installing node package manager
      working-directory: ./Frontend/my-portfolio
      run: npm install

    - name: Install dependencies...
      working-directory: ./Frontend/my-portfolio
      run: | 
       npm ci
       npm install react-device-detect --save


    - name: Building React app...
      working-directory: ./Frontend/my-portfolio
      run: |
        npm run build
        ls


    - name: Deploy
      working-directory: ./Frontend/my-portfolio
      run: |
        git config --global user.name 'Hiransanjeewa'
        git config --global user.email 'hiransanjeewaa@gmail.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}    
        npm run deploy
        




 build:
    name: Deploying in EC2

    runs-on: ubuntu-latest
    
   

    steps:
    - uses: actions/checkout@v3
 

    
    # - uses: actions/checkout@v2
    # - name: Test the Docker image
    #   run: docker-compose up 

 
    
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build the React Docker image
      run : |
        docker-compose build frontend    
        

    
    - name: Build the Express Docker image
      run : |  
       docker-compose build backend   
      
    - name: Pushing images to Dockerhub
      run : |  
       docker-compose push


    - name: Deploy to EC2 instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.EC2_INSTANCE_IP }}
        username: ${{ env.SSH_USERNAME }}
        key: ${{ env.SSH_PRIVATE_KEY }}
        script: |
         sudo apt update
         sudo apt install nodejs
         sudo apt install -y docker.io
     
        

         
        

         # Removing previous verions
            
         sudo docker stop my-server-container
         sudo docker stop my-client-container
         sudo docker rm my-client-container
         sudo docker rm my-server-container
         
        
         sudo docker rmi hiransanjeewa/portfolio_server:latest
         sudo docker rmi hiransanjeewa/portfolio_client:latest


         # Pull the Docker Hub images
         
         sudo docker pull hiransanjeewa/portfolio_server:latest
         sudo docker pull hiransanjeewa/portfolio_client:latest
         # Add more pull commands as needed
         
         
        
         
        
         # Starting Applications

         sudo docker run -d -p 8080:8080 --name my-server-container hiransanjeewa/portfolio_server:latest

         sudo docker run -d -p 3000:3000  --name my-client-container hiransanjeewa/portfolio_client:latest
         sudo docker image prune
         sudo docker container prune
        
      


        #  sudo docker stop 3a9f0353de7b
        #  sudo docker start 3a9f0353de7b 
        
        # running mongodb 
        # sudo docker pull mongo:latest
        # sudo docker volume create my-volume
        # sudo docker run -d -p 27017:27017 -v my-volume:/data/db -d mongo


        # Ngnix configurations
        # sudo apt update

#         sudo apt install nginx
#         sudo systemctl start nginx
#         sudo systemctl enable nginx
#         sudo nano /etc/nginx/nginx.conf
#         chmod options permissions file

#         http {
  # server {
  #   listen 80;

  #   location / {
  #     proxy_pass http://localhost:3000;
  #     proxy_set_header Host $host;
  #     proxy_set_header X-Real-IP $remote_addr;
  #   }

  #   location /api {
  #     proxy_pass http://localhost:8080;
  #     proxy_set_header Host $host;
  #     proxy_set_header X-Real-IP $remote_addr;
  #   }
  # }
# } in this settings how to run my containers
# change the localhost with the public ip of the instance
