name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: [  "main" ]


env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  IMAGE_NAME: hiransanjeewa/portfolio
  
  EC2_INSTANCE_IP:  ${{ secrets.EC2_HOST }}     
  SSH_USERNAME: ubuntu
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:

  build:

    runs-on: ubuntu-latest
    
   

    steps:
    - uses: actions/checkout@v3
 

    
    # - uses: actions/checkout@v2
    # - name: Test the Docker image
    #   run: docker-compose up 

 
    
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build the Docker image
      run : |
       docker-compose build
       docker images
       docker-compose push



      #  docker-compose build --no-cache --force-rm --build-arg IMAGE_TAG=hiransanjeewa/portfolio:latest
      #  docker-compose push
      #  ls

    - name: Deploy to EC2 instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.EC2_INSTANCE_IP }}
        username: ${{ env.SSH_USERNAME }}
        key: ${{ env.SSH_PRIVATE_KEY }}
        script: |
         sudo apt-get update
         sudo apt-get install -y curl jq

         sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
         sudo chmod +x /usr/local/bin/docker-compose
         docker-compose --version

         sudo docker pull hiransanjeewa/portfolio:latest
         sudo docker-compose up


        #  sudo apt update
        #  sudo apt install nodejs
        #  sudo apt install -y docker.io
        #  sudo docker stop 3a9f0353de7b
        #  sudo docker start 3a9f0353de7b 
        
        

        #  # Removing previous verions
        #  sudo docker stop my-client-container
        #  sudo docker stop my-server-container
        #  sudo docker rm my-client-container
        #  sudo docker rm my-server-container
         
        #  sudo docker rmi hiransanjeewa/portfolio_client:latest
        #  sudo docker rmi hiransanjeewa/portfolio_server:latest


        #  # Pull the Docker Hub images
        #  sudo docker pull hiransanjeewa/portfolio_client:latest
        #  sudo docker pull hiransanjeewa/portfolio_server:latest
        #  # Add more pull commands as needed
         
        
         
        
        #  # Starting Applications

        #  sudo docker run -d   -p 80:3000 --name=my-client-container hiransanjeewa/portfolio_client:latest

        #  sudo docker run -d   -p 8080:443 --name=my-server-container hiransanjeewa/portfolio_server:latest
        #  sudo docker image prune
        #  sudo docker container prune
        
        
    
 #  sudo docker pull mongo:latest
        #  mkdir mongodbsrc
        #  sudo docker run -d -p 27017:27017 -v ~/mongodbsrc:/data/db --name mongodb mongo
        #  mkdir backup
        #  cd backup
        #  curl -LO https://raw.githubusercontent.com/Hiransanjeewa/my_portfolio/main/my_portfolio_db
        #  sudo docker run --rm -v $(pwd):/backup mongo mongorestore --host mongodb --port 27017 --db my_portfolio /backup
         
   
         
         
       

