name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: [  "main" ]

  


env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: hiransanjeewa/portfolio
  EC2_INSTANCE_IP:  54.86.186.59
  SSH_USERNAME: ubuntu
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:

  build:

    runs-on: ubuntu-latest
    
   

    steps:
    - uses: actions/checkout@v3
 

    
    # - uses: actions/checkout@v2
    # - name: Test the Docker image
    #   run: docker-compose up 

 
    
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build the Docker image
      run : |
       docker-compose build --no-cache --force-rm --build-arg IMAGE_TAG=hiransanjeewa/portfolio:latest
       docker-compose push
       ls

    - name: Deploy to EC2 instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.EC2_INSTANCE_IP }}
        username: ${{ env.SSH_USERNAME }}
        key: ${{ env.SSH_PRIVATE_KEY }}
        script: |
         sudo apt update
         sudo apt install -y docker.io
        
         # Pull the Docker Hub images
         sudo docker pull hiransanjeewa/portfolio_client:latest
         sudo docker pull hiransanjeewa/portfolio_server:latest
         # Add more pull commands as needed
         
        
         # Start the containers
        
         sudo docker stop my-client-container
         sudo docker stop my-server-container
         sudo docker rm my-client-container
         sudo docker rm my-server-container
         

         

         sudo docker run -d -p 80:3000 --name=my-client-container hiransanjeewa/portfolio_client:latest

         sudo docker run -d -p 8080:8080 --name=my-server-container hiransanjeewa/portfolio_server:latest
         sudo docker image prune
         sudo docker container prune
        
        
          
    

   
         
         
       

      # - name: Change directory to my_portfolio
        # run: cd Frontend/Frontend/my_portfolio
